---
- hosts: localhost
  vars:
    mysql_root_password: fr0299
    db_name: cattle
    db_user: cattle
    db_pass: 12345
    db_admin_user: root
    db_admin_pass: fr0299
    db_host: localhost
    db_port: 3306
  
  tasks:
    - name: Install MySQL Server
      become: true
      apt: name=mysql-server update_cache=yes cache_valid_time=3600 state=present
    
    - name: Install Python MySQL
      become: true
      apt: name=python-mysqldb update_cache=yes cache_valid_time=3600 state=present
    
    - name: Start the MySQL service
      become: true
      service: 
        name: mysql
        state: started
        enabled: true

    - name: Update mysql root password for all root accounts
      become: true
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
    
    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        collation: utf8_general_ci
        encoding: utf8
        login_host: "{{ db_host }}"
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_pass }}"
        login_port: "{{ db_port }}"
        state: present
    
    - name: Create the database user
      become: true
      mysql_user:
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_pass }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        host: '%'
        priv: "*.*:ALL"
        state: present

